package greendao.utils;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.utils.Note;
import greendao.utils.Seq;

import greendao.utils.NoteDao;
import greendao.utils.SeqDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig seqDaoConfig;

    private final NoteDao noteDao;
    private final SeqDao seqDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        seqDaoConfig = daoConfigMap.get(SeqDao.class).clone();
        seqDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        seqDao = new SeqDao(seqDaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(Seq.class, seqDao);
    }
    
    public void clear() {
        noteDaoConfig.getIdentityScope().clear();
        seqDaoConfig.getIdentityScope().clear();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public SeqDao getSeqDao() {
        return seqDao;
    }

}
