package greendao.utils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "NOTE".
 */
public class Note implements Serializable{

    private Long id;
    private String title;
    private String content;
    private Integer backgroundColor;
    private Boolean isLike;
    private java.util.Date createDate;
    private java.util.Date notifyDate;
    private String Tag;
    private Integer type;

    public Note() {
    }

    public Note(Long id) {
        this.id = id;
    }

    public Note(Long id, String title, String content, Integer backgroundColor, Boolean isLike, java.util.Date createDate, java.util.Date notifyDate, String Tag, Integer type) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.backgroundColor = backgroundColor;
        this.isLike = isLike;
        this.createDate = createDate;
        this.notifyDate = notifyDate;
        this.Tag = Tag;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getBackgroundColor() {
        return backgroundColor;
    }

    public void setBackgroundColor(Integer backgroundColor) {
        this.backgroundColor = backgroundColor;
    }

    public Boolean getIsLike() {
        return isLike;
    }

    public void setIsLike(Boolean isLike) {
        this.isLike = isLike;
    }

    public java.util.Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(java.util.Date createDate) {
        this.createDate = createDate;
    }

    public java.util.Date getNotifyDate() {
        return notifyDate;
    }

    public void setNotifyDate(java.util.Date notifyDate) {
        this.notifyDate = notifyDate;
    }

    public String getTag() {
        return Tag;
    }

    public void setTag(String Tag) {
        this.Tag = Tag;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
