package greendao.utils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "SEQ".
 */
public class Seq implements Serializable{

    private Long id;
    private String orderId;

    public Seq() {
    }

    public Seq(Long id) {
        this.id = id;
    }

    public Seq(Long id, String orderId) {
        this.id = id;
        this.orderId = orderId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

}
